### PR TITLE
Add express and init server

### PR DESCRIPTION
**Pull request by bonustrack**
Changes:
- Add express
- Set "start" script with express server
- Display current head

image

### CODE REVIEW

**Comment by Sekhmet** [comment]
I wonder if this would be useful, as busy-db would be used for syncing blocks and inserting data into database and won't serve as API (or would it be API as well?)

**Comment by bonustrack** [comment]
I don't know if the API has to use the same codebase than `budy-db` but we will need to serve an API and the database should be on same server for latency reasons so i figured out it wouln't mind to have it on same codebase.

**Comment by Sekhmet** [comment]
I would focus this tool on only syncing blocks to DB. API would be different tool, but it would connect to the same database.

**Comment by bonustrack** [comment]
What if we make the indexer and API into a single repo for make it easier for dev and test until it's ready for production @Sekhmet ?

**Comment by Sekhmet** [comment]
I would use single repo for this, but I don't think that running API and sync in the same app is good idea.

**Comment by feruzm** [comment]
You could use servers from same data center which would have lowest latency, that way db and api could be on separate machine but close to each other.

**Pull request closed without merging**
